import {
  User,
  Item,
  AvailabilityBlock,
  BorrowRequest,
  Transaction,
  LostItem,
  FoundItem,
  CreditTransaction,
  RedemptionOption,
  Badge,
} from './types';

export const BADGES: Badge[] = [
  { id: 'b1', name: 'First Lend', description: 'Lent your first item', icon: 'star', earned: true },
  { id: 'b2', name: 'Trustworthy', description: 'Reached trust score 90+', icon: 'shield', earned: true },
  { id: 'b3', name: 'Good Samaritan', description: 'Helped an urgent request', icon: 'heart', earned: true },
  { id: 'b4', name: 'Lost & Found Hero', description: 'Returned a lost item', icon: 'search', earned: false },
  { id: 'b5', name: 'Super Lender', description: 'Lent 10+ items', icon: 'award', earned: false },
  { id: 'b6', name: 'On-Time Champion', description: '10 on-time returns in a row', icon: 'clock', earned: false },
];

export const MOCK_USERS: User[] = [
  {
    id: 'ayaan',
    name: 'Ayaan',
    grade: 9,
    trustScore: 95,
    credits: 120,
    pickupLocation: 'Library',
    avatar: 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Man%20Student.png',
    itemsLent: 8,
    itemsBorrowed: 3,
    onTimeReturns: 11,
    badges: BADGES,
  },
  {
    id: 'kevin',
    name: 'Kevin',
    grade: 10,
    trustScore: 88,
    credits: 75,
    pickupLocation: 'Cafeteria',
    avatar: 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Man%20Student.png',
    itemsLent: 4,
    itemsBorrowed: 6,
    onTimeReturns: 9,
    badges: BADGES.slice(0, 2),
  },
  {
    id: 'maya',
    name: 'Maya',
    grade: 11,
    trustScore: 92,
    credits: 100,
    pickupLocation: 'Room 210',
    avatar: 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Woman%20Technologist.png',
    itemsLent: 6,
    itemsBorrowed: 2,
    onTimeReturns: 8,
    badges: BADGES.slice(0, 3),
  },
  {
    id: 'sam',
    name: 'Sam',
    grade: 9,
    trustScore: 80,
    credits: 40,
    pickupLocation: 'Gym',
    avatar: 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Man%20Mechanic.png',
    itemsLent: 2,
    itemsBorrowed: 5,
    onTimeReturns: 4,
    badges: BADGES.slice(0, 1),
  },
  {
    id: 'elena',
    name: 'Elena',
    grade: 12,
    trustScore: 97,
    credits: 180,
    pickupLocation: 'STEM Lab',
    avatar: 'https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/People/Woman%20Student.png',
    itemsLent: 15,
    itemsBorrowed: 1,
    onTimeReturns: 16,
    badges: BADGES,
  },
];

export const CURRENT_USER = MOCK_USERS[0]; // Ayaan

export const MOCK_AVAILABILITY: AvailabilityBlock[] = [
  { id: 'av1', userId: 'ayaan', day: 'Monday', startTime: '11:20', endTime: '11:50', location: 'Cafeteria', type: 'lunch' },
  { id: 'av2', userId: 'ayaan', day: 'Monday', startTime: '15:00', endTime: '15:30', location: 'Library', type: 'after-school' },
  { id: 'av3', userId: 'kevin', day: 'Monday', startTime: '11:20', endTime: '11:50', location: 'Cafeteria', type: 'lunch' },
  { id: 'av4', userId: 'kevin', day: 'Tuesday', startTime: '15:00', endTime: '15:30', location: 'Library', type: 'after-school' },
  { id: 'av5', userId: 'maya', day: 'Monday', startTime: '10:20', endTime: '11:15', location: 'Room 210', type: 'free-period' },
  { id: 'av6', userId: 'maya', day: 'Monday', startTime: '15:00', endTime: '16:00', location: 'STEM Lab', type: 'after-school' },
  { id: 'av7', userId: 'sam', day: 'Monday', startTime: '12:15', endTime: '12:45', location: 'Gym', type: 'lunch' },
  { id: 'av8', userId: 'sam', day: 'Tuesday', startTime: '11:20', endTime: '11:50', location: 'Cafeteria', type: 'lunch' },
  { id: 'av9', userId: 'elena', day: 'Monday', startTime: '11:25', endTime: '11:45', location: 'Library', type: 'lunch' },
  { id: 'av10', userId: 'elena', day: 'Friday', startTime: '15:00', endTime: '15:45', location: 'STEM Lab', type: 'after-school' },
];

export const MOCK_ITEMS: Item[] = [
  {
    id: 'item1',
    name: 'TI-84 Plus CE Calculator',
    category: 'calculator',
    description: 'Graphing calculator in great condition. Has a protective case.',
    condition: 'excellent',
    ownerId: 'ayaan',
    ownerName: 'Ayaan',
    ownerTrustScore: 95,
    pickupLocation: 'Library',
    availableDays: ['Monday'],
    availableStart: '11:20',
    availableEnd: '11:50',
    availabilityLabel: 'Monday Lunch A',
    isExpensive: true,
    rules: 'Please return with the case.',
    isAvailable: true,
    listedAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'item2',
    name: 'USB-C Charger',
    category: 'charger',
    description: '65W USB-C charger, works with most laptops and phones.',
    condition: 'good',
    ownerId: 'kevin',
    ownerName: 'Kevin',
    ownerTrustScore: 88,
    pickupLocation: 'Cafeteria',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availableStart: '15:00',
    availableEnd: '15:30',
    availabilityLabel: 'After School',
    isExpensive: false,
    isAvailable: true,
    listedAt: '2024-01-14T10:00:00Z',
  },
  {
    id: 'item3',
    name: 'Safety Goggles',
    category: 'science',
    description: 'Clear safety goggles, cleaned and sanitized.',
    condition: 'good',
    ownerId: 'maya',
    ownerName: 'Maya',
    ownerTrustScore: 92,
    pickupLocation: 'STEM Lab',
    availableDays: ['Monday'],
    availableStart: '10:20',
    availableEnd: '11:15',
    availabilityLabel: 'Monday Free Period',
    isExpensive: false,
    isAvailable: true,
    listedAt: '2024-01-13T11:00:00Z',
  },
  {
    id: 'item4',
    name: 'Graph Paper Pack',
    category: 'school-supply',
    description: '50 sheets of graph paper, standard grid.',
    condition: 'excellent',
    ownerId: 'elena',
    ownerName: 'Elena',
    ownerTrustScore: 97,
    pickupLocation: 'Library',
    availableDays: ['Monday', 'Friday'],
    availableStart: '11:25',
    availableEnd: '11:45',
    availabilityLabel: 'Mon / Fri Lunch',
    isExpensive: false,
    isAvailable: true,
    listedAt: '2024-01-12T08:00:00Z',
  },
  {
    id: 'item5',
    name: 'Robotics Screwdriver Kit',
    category: 'robotics',
    description: '12-piece precision screwdriver set for electronics.',
    condition: 'excellent',
    ownerId: 'maya',
    ownerName: 'Maya',
    ownerTrustScore: 92,
    pickupLocation: 'STEM Lab',
    availableDays: ['Monday'],
    availableStart: '15:00',
    availableEnd: '16:00',
    availabilityLabel: 'Monday After School',
    isExpensive: true,
    rules: 'Return all 12 pieces.',
    isAvailable: true,
    listedAt: '2024-01-11T13:00:00Z',
  },
  {
    id: 'item6',
    name: 'Tripod',
    category: 'media',
    description: 'Adjustable tripod, works with phones and small cameras.',
    condition: 'good',
    ownerId: 'sam',
    ownerName: 'Sam',
    ownerTrustScore: 80,
    pickupLocation: 'Gym',
    availableDays: ['Monday'],
    availableStart: '12:15',
    availableEnd: '12:45',
    availabilityLabel: 'Monday Lunch B',
    isExpensive: false,
    isAvailable: true,
    listedAt: '2024-01-10T14:00:00Z',
  },
  {
    id: 'item7',
    name: 'Ruler (12-inch)',
    category: 'school-supply',
    description: 'Clear plastic ruler with both metric and imperial.',
    condition: 'excellent',
    ownerId: 'ayaan',
    ownerName: 'Ayaan',
    ownerTrustScore: 95,
    pickupLocation: 'Cafeteria',
    availableDays: ['Monday'],
    availableStart: '11:20',
    availableEnd: '11:50',
    availabilityLabel: 'Monday Lunch A',
    isExpensive: false,
    isAvailable: true,
    listedAt: '2024-01-09T09:30:00Z',
  },
  {
    id: 'item8',
    name: 'Glue Gun',
    category: 'art',
    description: 'Mini hot glue gun with 5 glue sticks included.',
    condition: 'good',
    ownerId: 'elena',
    ownerName: 'Elena',
    ownerTrustScore: 97,
    pickupLocation: 'STEM Lab',
    availableDays: ['Friday'],
    availableStart: '15:00',
    availableEnd: '15:45',
    availabilityLabel: 'Friday After School',
    isExpensive: false,
    isAvailable: true,
    listedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: 'item9',
    name: 'Laptop Stand',
    category: 'tech',
    description: 'Foldable aluminum laptop stand, adjustable height.',
    condition: 'excellent',
    ownerId: 'kevin',
    ownerName: 'Kevin',
    ownerTrustScore: 88,
    pickupLocation: 'Cafeteria',
    availableDays: ['Tuesday'],
    availableStart: '15:00',
    availableEnd: '15:30',
    availabilityLabel: 'Tuesday After School',
    isExpensive: false,
    isAvailable: true,
    listedAt: '2024-01-07T11:00:00Z',
  },
  {
    id: 'item10',
    name: 'Soccer Cleats (Size 9)',
    category: 'sports',
    description: 'Nike soccer cleats, size 9, barely used.',
    condition: 'good',
    ownerId: 'sam',
    ownerName: 'Sam',
    ownerTrustScore: 80,
    pickupLocation: 'Gym',
    availableDays: ['Tuesday'],
    availableStart: '11:20',
    availableEnd: '11:50',
    availabilityLabel: 'Tuesday Lunch',
    isExpensive: true,
    rules: 'Clean before returning please.',
    isAvailable: true,
    listedAt: '2024-01-06T12:00:00Z',
  },
];

export const MOCK_REQUESTS: BorrowRequest[] = [
  {
    id: 'req1',
    requesterId: 'kevin',
    requesterName: 'Kevin',
    itemCategory: 'calculator',
    itemName: 'TI-84 Calculator',
    day: 'Monday',
    startTime: '11:20',
    endTime: '11:50',
    period: '5th Period',
    urgency: 'normal',
    preferredLocation: 'Cafeteria',
    status: 'matched',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    matchedItemId: 'item1',
    matchedUserId: 'ayaan',
  },
  {
    id: 'req2',
    requesterId: 'sam',
    requesterName: 'Sam',
    itemCategory: 'science',
    itemName: 'Safety Goggles',
    day: 'Monday',
    startTime: '10:20',
    endTime: '11:15',
    period: '3rd Period',
    urgency: 'urgent',
    preferredLocation: 'STEM Lab',
    status: 'approved',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    matchedItemId: 'item3',
    matchedUserId: 'maya',
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn1',
    itemId: 'item2',
    itemName: 'USB-C Charger',
    borrowerId: 'ayaan',
    borrowerName: 'Ayaan',
    lenderId: 'kevin',
    lenderName: 'Kevin',
    checkoutTime: new Date(Date.now() - 7200000).toISOString(),
    dueTime: new Date(Date.now() + 3600000).toISOString(),
    status: 'active',
    pickupLocation: 'Cafeteria',
  },
  {
    id: 'txn2',
    itemId: 'item7',
    itemName: 'Ruler',
    borrowerId: 'maya',
    borrowerName: 'Maya',
    lenderId: 'ayaan',
    lenderName: 'Ayaan',
    checkoutTime: new Date(Date.now() - 86400000).toISOString(),
    dueTime: new Date(Date.now() - 3600000).toISOString(),
    returnTime: new Date(Date.now() - 3000000).toISOString(),
    status: 'returned',
    pickupLocation: 'Cafeteria',
    creditsAwarded: 15,
  },
];

export const MOCK_LOST_ITEMS: LostItem[] = [
  {
    id: 'lost1',
    reporterId: 'kevin',
    reporterName: 'Kevin',
    itemName: 'USB-C Charger',
    category: 'charger',
    description: 'White USB-C charger with a small scratch on the plug end.',
    lastSeenLocation: 'Library',
    timeLost: '2024-01-15T09:30:00Z',
    uniqueDetail: 'Has a small blue sticker on the cable',
    status: 'active',
    reportedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'lost2',
    reporterId: 'sam',
    reporterName: 'Sam',
    itemName: 'Scientific Calculator',
    category: 'calculator',
    description: 'Black Casio fx-300ES calculator.',
    lastSeenLocation: 'Math Classroom 105',
    timeLost: '2024-01-14T14:00:00Z',
    uniqueDetail: '"SAM" written on the back in marker',
    status: 'active',
    reportedAt: '2024-01-14T15:00:00Z',
  },
];

export const MOCK_FOUND_ITEMS: FoundItem[] = [
  {
    id: 'found1',
    reporterId: 'maya',
    reporterName: 'Maya',
    itemName: 'USB-C Charger',
    category: 'charger',
    description: 'White USB-C charger found near the library tables.',
    locationFound: 'Library',
    timeFound: '2024-01-15T11:00:00Z',
    verificationDetail: 'Cable has a distinctive sticker',
    status: 'unclaimed',
    reportedAt: '2024-01-15T11:15:00Z',
  },
  {
    id: 'found2',
    reporterId: 'elena',
    reporterName: 'Elena',
    itemName: 'Notebook',
    category: 'school-supply',
    description: 'Blue spiral notebook with "Chemistry" written on it.',
    locationFound: 'Cafeteria',
    timeFound: '2024-01-15T12:00:00Z',
    verificationDetail: 'Has name on inside cover',
    status: 'unclaimed',
    reportedAt: '2024-01-15T12:10:00Z',
  },
];

export const MOCK_CREDIT_HISTORY: CreditTransaction[] = [
  { id: 'ct1', userId: 'ayaan', amount: 15, reason: 'Lent TI-84 to Kevin', type: 'earned', timestamp: new Date(Date.now() - 86400000).toISOString() },
  { id: 'ct2', userId: 'ayaan', amount: 10, reason: 'On-time return by Maya', type: 'earned', timestamp: new Date(Date.now() - 172800000).toISOString() },
  { id: 'ct3', userId: 'ayaan', amount: 20, reason: 'Helped urgent request from Sam', type: 'earned', timestamp: new Date(Date.now() - 259200000).toISOString() },
  { id: 'ct4', userId: 'ayaan', amount: 15, reason: 'Lent Ruler to Maya', type: 'earned', timestamp: new Date(Date.now() - 345600000).toISOString() },
  { id: 'ct5', userId: 'ayaan', amount: 10, reason: 'Reported found safety goggles', type: 'earned', timestamp: new Date(Date.now() - 432000000).toISOString() },
  { id: 'ct6', userId: 'ayaan', amount: -10, reason: 'Late return of USB hub', type: 'spent', timestamp: new Date(Date.now() - 518400000).toISOString() },
  { id: 'ct7', userId: 'ayaan', amount: 30, reason: 'Redeemed: School store coupon', type: 'spent', timestamp: new Date(Date.now() - 604800000).toISOString() },
];

export const REDEMPTION_OPTIONS: RedemptionOption[] = [
  { id: 'r1', name: 'School Store Coupon', description: '$2 off at the school store', cost: 30, icon: 'tag' },
  { id: 'r2', name: 'Priority Borrowing', description: 'Jump to the top of request queue for 1 week', cost: 50, icon: 'zap' },
  { id: 'r3', name: 'Club Raffle Entry', description: 'One entry into the monthly club raffle', cost: 40, icon: 'gift' },
  { id: 'r4', name: 'Lunch Line Fast Pass', description: 'Skip the lunch line once (Fri only)', cost: 60, icon: 'star' },
  { id: 'r5', name: 'Profile Badge', description: 'Earn an exclusive profile badge', cost: 25, icon: 'award' },
];

export const LEADERBOARD = MOCK_USERS.sort((a, b) => b.credits - a.credits).map((u, i) => ({
  rank: i + 1,
  ...u,
}));

export const ACTIVITY_FEED = [
  { id: 'a1', text: 'Maya returned your Ruler', time: '2 hours ago', type: 'return', icon: 'check-circle' },
  { id: 'a2', text: 'Kevin requested your TI-84 Calculator', time: '3 hours ago', type: 'request', icon: 'inbox' },
  { id: 'a3', text: 'You earned 15 credits for lending', time: '1 day ago', type: 'credit', icon: 'dollar-sign' },
  { id: 'a4', text: 'Elena reported a found USB-C Charger', time: '1 day ago', type: 'found', icon: 'search' },
  { id: 'a5', text: 'Your trust score increased to 95', time: '2 days ago', type: 'trust', icon: 'trending-up' },
];
